# Generated by Django 3.2.8 on 2021-10-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('rating', models.IntegerField()),
                ('poster_url', models.CharField(max_length=200)),
                ('synoposis', models.IntegerField(default=3)),
                ('cast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.person')),
            ],
        ),
    ]
