# Generated by Django 3.2.8 on 2021-10-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(),
        ),
    ]
