# Generated by Django 3.2.8 on 2021-10-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five')]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synoposis',
            field=models.TextField(),
        ),
    ]
