# Generated by Django 3.2.8 on 2021-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('release_date', 'movie_title')},
        ),
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male'), ('X', 'Unknown')], default='X', max_length=1),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'NR - Not Rate'), (1, 'G - General Audiences'), (2, 'PG – Parental Guidance Suggested'), (3, 'PG-13 – Parents Strongly Cautioned'), (4, 'R – Restricted'), (5, 'NC-17 – Adults Only')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='First Name', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=200),
        ),
    ]
