# Generated by Django 3.2.8 on 2021-10-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'NR - Not Rate'), (1, 'G - General Audiences'), (2, 'PG – Parental Guidance Suggested'), (3, 'PG-13 – Parents Strongly Cautioned'), (4, 'NC-16 – No Children under 16'), (5, 'M-18 – Restricted to persons 18 years and above'), (6, 'R21 – Strictly for adults aged 21 and above')], default=0),
        ),
    ]
